# Generated by Django 3.2.3 on 2021-05-31 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210531_1006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
