# Generated by Django 3.2.3 on 2021-06-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycolleges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='category',
        ),
        migrations.AlterField(
            model_name='college',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
