# Generated by Django 3.2.3 on 2021-06-06 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycolleges', '0005_alter_college_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='college',
            managers=[
            ],
        ),
    ]
