# Generated by Django 3.2.3 on 2021-06-06 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycolleges', '0006_alter_college_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='user',
        ),
    ]
